import { writable } from "svelte/store"

export let video = writable ([
    {
        id: 1,
        user: "",
        nomecanale: "Traversy Media",
        immagineprofilo: "/video/traversy.jpg",
        niscritti: "2,12 Mln",
        titolovideo: "CSS Text Background Animation",
        visualizzazioni: "65.152",
        durata: "11:14",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/cssanimation.jpg",
        videoclip: "/video/CSSAnimation.mp4",
        banner: "/video/BannerTrav.png",
        descrizione: "Traversy Media features the best online web development and programming tutorials for all of the latest web technologies from the building blocks of HTML, CSS & JavaScript to frontend frameworks like React and Vue to backend technologies like Node.js, Python and PHP",
        dataiscrizione: "30 ott 2009",
    },
    {
        id: 2,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 1 - What is SvelteKit",
        visualizzazioni: "88.679",
        durata: "6:31",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja1.jpg",
        videoclip: "/video/SvelteKit1.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
    {
        id: 3,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 2 - Setting up a SvelteKit App",
        visualizzazioni: "38.284",
        durata: "6:21",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja2.jpg",
        videoclip: "/video/SvelteKit2.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
    {
        id: 4,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 3 - Svelte Components (refresh)",
        visualizzazioni: "28.162",
        durata: "8:45",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja3.jpg",
        videoclip: "/video/SvelteKit3.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
    {
        id: 5,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 4 - Pages & Routes",
        visualizzazioni: "26.017",
        durata: "10:26",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja4.jpg",
        videoclip: "/video/SvelteKit4.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
    {
        id: 6,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 5 - Reusable Components",
        visualizzazioni: "19.482",
        durata: "7:33",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja5.jpg",
        videoclip: "/video/SvelteKit5.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
    {
        id: 7,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 6 - Layout Components",
        visualizzazioni: "17.875",
        durata: "8:21",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja6.jpg",
        videoclip: "/video/SvelteKit6.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
    {
        id: 8,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 7 - Reset Layouts",
        visualizzazioni: "15.145",
        durata: "5:32",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja7.jpg",
        videoclip: "/video/SvelteKit7.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
    {
        id: 9,
        user: "",
        nomecanale: "The Net Ninja",
        immagineprofilo: "/video/netninja.jpg",
        niscritti: "1,18 Mln",
        titolovideo: "SvelteKit Crash Course Tutorial 8 - Loading Data & SSR",
        visualizzazioni: "22.147",
        durata: "9:51",
        like: false,
        iscriviti: false,
        copertinavideo: "/video/netninja8.jpg",
        videoclip: "/video/SvelteKit8.mp4",
        banner: "/video/BannerNet.png",
        descrizione: "Black-belt your web development skills. Over 2000 free programming tutorial videos",
        dataiscrizione: "8 apr 2015",
    },
]);